### ISSUE TITLE
Creating the entry in the aspnetusers table manually

### ISSUE THREAD

**Issue by ssteiner** [MohammadYounes/OWIN-MixedAuth#25]
Hi

I noted that if a user logs in, he/she gets an entry in the ASPNetUsers table, just like local users. I was wondering what kind of data need to be added to do this prior to the user logging in. I'm devising a system with local roles and I'd like to be able to assign them prior to the user first logging in, but to do that, I need the entry in the ASPNetUsers table (and create one if there's none present).

Thanks
Stephan

**Comment by MohammadYounes** [comment]
Hi,

This is the default ASPNET identity behavior, all external logins require a local account. The difference is the local account is created without a password. 

Any updates you want to apply to newly created accounts can be done [upon account creation](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L374).

Thanks.

**Comment by ssteiner** [comment]
I don't mind having that entry - I'm more curious how that record is created so that I could generate it on my own (prior to the user logging in).

**Comment by MohammadYounes** [comment]
This statement [`UserManager.CreateAsync(user);`](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/MVC/Controllers/AccountController.cs#L374) is the one responsible for creating that record. Internally it calls the `UserStore.CreateAsync` which in turn creates the DB record.

**Comment by brianlagerman** [comment]
We also had to prepopulate the User and UserLogin tables with AD Accounts, so in addition to calling UserManager.CreateAsync() we hit UserManager.AddLoginAsync() as well.

For example, we pulled all the users from AD with something similar to the following, and then just built the user and login objects from the AD values:

using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using (var context = new PrincipalContext(ContextType.Domain, "YOUR_DOMAIN_NAME"))
            {
                using (var searcher = new PrincipalSearcher(new UserPrincipal(context)))
                {
                    foreach (var result in searcher.FindAll())
                    {
                        DirectoryEntry de = result.GetUnderlyingObject() as DirectoryEntry;
                        Console.WriteLine("First Name: " + de.Properties["givenName"].Value);
                        Console.WriteLine("Last Name : " + de.Properties["sn"].Value);
                        Console.WriteLine("SAM account name   : " + de.Properties["samAccountName"].Value);
                        Console.WriteLine("User principal name: " + de.Properties["userPrincipalName"].Value);
                        Console.WriteLine();
                    }
                }
            }

**Comment by sacocelarc** [comment]
I still don't understand how can I prepopulate AspNetUsers table with user records and pair them with AD accounts/ in my case it is Windows 10 development machine.
 
So ... Test case of OWIN-MixedAuth shows us the case when AD/Windows user authenticate using Windows authentication. And when this is first time user is redirected to confirmation page where he enters mail address and hit the Register button which calls the   ExternalLoginConfirmation method of AccountController.
An here is called 
1. await UserManager.CreateAsync(user) 
which (if I understand correctly) creates record in AspNetUsers table
and then is called 
2. await UserManager.AddLoginAsync(user.Id, info.Login)   
which (if I understand correctly) connects/pairs this record with AD/windows account.

But how can I do it manually in the background for some users in AD (or some  windows accounts of my local machine)?
I assume that this email address is an attribute which connects   AspNetUsers table and AD/windows account. But where on AD/windows can be seen this email?

**Comment by brianlagerman** [comment]
I'm a little surprised that you're still using this code base considering it's age. If you're building an Intranet application, this might be fine, but if any external access is required you'll be opening a can of worms. I would highly recommend looking at some newer security packages, like passport for example, which will give you far more options with much better security.

But, if you still want to proceed with this, the 'email' you're looking for is the userPrincipalName in the code above. Note that this might also be their email address, but doesn't have to be. It is, however, what is matched against AD.

As for:
>  (or some windows accounts of my local machine)

Give up on that right away. Your local machine would be another provider, and won't translate over well to your web server

**Comment by sacocelarc** [comment]
Brian, thank you to respond.
Yes, I have the requirement to develop authentication for ASP.NET MVC 5 application where some users are logged as domain users (in AD) inside the organisation LAN  and other users come from internet ... and domain users should be logged in automatically by Windows authentication and internet users hould be logged in by Forms Authentication. All users are known in advance, so no self registration is allowed.
All internet resources about this topic point to OWIN-MixedAuth. So I am here, with little malnourished knowledge of Microsoft infrastructure (IIS, AD, ...) and ASP.NET Identity.    
Do you have suggestion for different approach, what did you mean with "like passport for example", is this some sort of Microsoft SSO? The organisation, I am working for, have somehow rigid approach regarding infrastructure changes ... they have what they have and don't want changes, so the authentication should be solved more or less programmatically.
Regards.

**Comment by brianlagerman** [comment]
Well, if you're bound by the current infrastructure then you might very well be in the right place.

I would first verify what flavor of AD is available to you (if you're not already sure). If you have either Active Directory Federation Services OR Azure Active Directory, then you really want to set up your domain users with the standard Oauth flow in ASP.NET Identity. It just saves a ton of trouble down the road.

If that's not possible, then this package probably is the right approach. Be aware of the following though:

- If your domain users will also need to log in remotely, then they will need to establish a VPN connection for Windows Authentication to work. This can feel very redundant since the web server is normally available without a VPN.

- If a VPN is not possible and you still need to provide remote access for domain users, you'll have to map an additional, non-domain login for each domain user. You can do this manually if your user count isn't too high, or build a self service login mapping page for domain users. It's not much fun either way, and your users may get confused as to which account to use when.

[Passport](http://www.passportjs.org/) doesn't seem applicable here as it runs on node.js, probably a bad suggestion on my part.   Just keep up to speed on the [Microsoft Authentication Libraries](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/about-microsoft-identity-platform) so that you can make the most of the infrastructure available to you.

**Comment by sacocelarc** [comment]
- they don't have avilable Active Directory Federation Services OR Azure Active Directory
- yes, they have VPN for remote work of domain users, so Windows Authentication should work
So I go OWIN-MixedAuth path.
Thank you for suggestions and directions.

**Comment by MohammadYounes** [comment]
@sacocelarc 

> But how can I do it manually in the background for some users in AD (or some windows accounts of my local machine)?
> I assume that this email address is an attribute which connects AspNetUsers table and AD/windows account. But where on AD/windows can be seen this email?

Users are linked via `objectSID`. To manually link identities, you need to add a record to `AspNetUserLogins` as follows:

| LoginProvider | ProviderKey |  UserId
|-----------------|--------------|-----------
| `Windows`       | `{AD objectSID}` | `{Aspnet User Id}`

Where  `{AD objectSID}` is the Active Directory user `objectSID` and `{Aspnet User Id}` is the local aspnet user id.

**Comment by sacocelarc** [comment]
Mohammad, thank you for this missing piece. When I study code in examples I realized when record in AspNetUsers is created. But I was not aware of role of AspNetUserLogins table.

So if summarize my understanding of workflow in example code:

1. Get information about Windows/AD account ... info.Login.ProviderKey is set by value of {AD objectSID}
`Using  var info = await AuthenticationManager.GetExternalLoginInfoAsync();`

2. Creates record in AspNetUsers with Id = generated UID
`var result = await UserManager.CreateAsync(user);`

3. Creates record in AspNetUserLogins which connects  {AD objectSID} and AspNetUsers record
`result = await UserManager.AddLoginAsync(user.Id, info.Login);`

And instead of allowing process of this self confirmation I can get {AD objectSID} value, create records in AspNetUsers and AspNetUserLogins **independently in advance**.

**Comment by MohammadYounes** [comment]
@sacocelarc Yes.
