### ISSUE TITLE
IIS setting

### ISSUE THREAD

**Issue by Saquibadil** [MohammadYounes/OWIN-MixedAuth#28]
Hello,

I see the IIS setting for the Windows Authentication is made at the server level. Is there a way to make this setting at the website level, because we have other websites hosted on the same server, I would prefer to make the setting on the website level.

Thank you

**Comment by MohammadYounes** [comment]
Hi,

The server setting is just to unlock the `windowsAuthentication` section, and it's required since it's the root we are trying to override! Another alternative is to enable Windows Authentication/Anonymous authentication on the website level and Deny Anonymous Authentication to the Windows Login Path.

Thanks.
