### ISSUE TITLE
Authenticate against API from windows app

### ISSUE THREAD

**Issue by MrBeezel** [MohammadYounes/OWIN-MixedAuth#54]
Hello,
I have been using the ASP example and I have a question
How can I get the API access token from a windows application? I know that in another email you told me that the Authorize end point is defined in /Account/Authorize but whenever I send a request to that path I get an error 400.

Thanks.

**Comment by MohammadYounes** [comment]
400 indicates a bad request, seems you didn't include all [required parameters](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/Scripts/app/app.viewmodel.js#L51).  The `client_id` should match the defined [ApplicationOAuthProvider public client Id](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L21)  and the `response_type` should be `token`.

In the SPA project, since you have already authenticated the user, the above would result in access token added as a fragment to the redirect url. 

However, In your Windows App, the user is still not authenticated. To Authenticate against the Windows provider using current Windows credentials,  You should hit the `ExternalLogin` endpoint with an additional parameter (`provider=Windows`) along with other `Authorize` endpoint params.

So the final url would look similar to:
 `api/Account/ExternalLogin?provider=Windows&response_type=token&client_id=myapp&redirect_uri=...&state=...`

Not sure if this is clear enough! Let me know if you need further assistance.

Thanks!

**Comment by MrBeezel** [comment]
Thanks, I got it to authenticate and get the corresponding token but I have located another problem. When I attempt to authenticate from outside the AD (for example, from a local account), it authenticates me instead of denying me access. Why does this happen?

**Comment by MohammadYounes** [comment]
Under which flow/account ? 

Moreover, what do you mean by:

> it authenticates me instead of denying me access

**Comment by MrBeezel** [comment]
Sorry for not being too clear.
The situation is this:
I have created an example windows application that only tries to authenticate against the API using its AD credentials.
When I run this application from a user account belonging to an AD, it authenticates me and gives me the corresponding token. But if I do the same from another user account that does not belong to that AD, it authenticates me too.

It is supposed that if a user does not belong to that AD, he should not be able to connect to the API, at least not through windows authentication.

And again, thanks!

**Comment by MohammadYounes** [comment]
Can you join here https://gitter.im/MohammadYounes/OWIN-MixedAuth ?

**Comment by MrBeezel** [comment]
Yeah, but right now I have to get out so you mind if we continue later?

**Comment by MohammadYounes** [comment]
Not sure if I will be available. Anyhow, It would be great if you could share a sample project presenting your scenario.

**Comment by MrBeezel** [comment]
Hi! 
I finally discovered the error. It was a configuration problem in my application that I already solved. Thank you very much for everything.
Just one more question,
Is it possible, in Windows Authentication mode, to get the name of the user who was authenticated? The idea is use that name to create the session in the web service instead of the email.
Again, thank you very much.

**Comment by MohammadYounes** [comment]
Sure, you can read the name upon user registration and add it to user claims as described in [Importing Custom Claims](https://github.com/MohammadYounes/OWIN-MixedAuth#importing-custom-claims).

Thanks!
