### ISSUE TITLE
Windows/AD authentication for WebAPI and SPA+Mobile clients

### ISSUE THREAD

**Issue by rezanos** [MohammadYounes/OWIN-MixedAuth#59]
Hi Mohammad,

I'm developing an application with WebAPI REST server and an SPA web client (Angular2) —both are ASP.NET 4.6 which created by empty template and both use OWIN and hosted on IIS.

The requirement for Authentication is:

- Active Directory logged in user will authenticated automatically with no need to enter username and pass, if her user Id/name found in the application database (simply AD users which exist in the database will permitted to log in and use the system). If AD user not found in the database it will redirect to the login form.
- There is a logout option which redirect to the login page after logging the user out.
- In the login page user can enter her AD username & password and after a successful checking against the AD she will logged in to the system as the entered user (Obviously it may differ with the user currently is logged in to the workstation)
- I addition to the web client there will be some other clients such as mobile apps which connect and serve by the WebAPI back-end. Users will login there using her AD user & pass too.

1. According to the architecture and the requirements (both AD enterprise and mobile internet user and WebAPI (REST), I found that the authentication should be token based at core.

2. I think your MixedAuth solution is the best/nearest solution for me. But even after deep dig into the  OWIN-MixedAuth middleware, your sample projects and googling and reading a lot about OWIN Authentication architecture and Windows Authentication in ASP.Net, I couldn't find my way.

What should I do on the Server and Client to accomplish this requirement?
How should I add and config MixedAuth and maybe OAuthBearerTokens MWs?
Is it necessary to use CookieAuthentication and ExternalSignInCookie MWs or not?

Please advice me.

Thanks a lot in advance.

**Comment by MohammadYounes** [comment]
@rnaab A couple of things to note here:

1. When using auto-login, user can't really logout unless browser process is closed to clear the credentials cache. However, you may try this approach: http://signinas.codeplex.com/ 

2. If users will be entering AD credentials in the login page, Then this is a regular cookies authentication (The only difference is that you are validating against AD rather than the DB).

3. Using bearer tokens is an extra option that you can enable on top of the existing authentication providers. see [SPA project](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L73)

That being said:

> What should I do on the Server and Client to accomplish this requirement?

* On the server: Normal configuration with bearer token authentication enabled.
* On the client:  The internet options security settings should not be set to anonymous : 
![auto login](https://cloud.githubusercontent.com/assets/4712046/6040904/b1c35c44-ac7f-11e4-9526-7086d71c058b.png)


> How should I add and config MixedAuth and maybe OAuthBearerTokens MWs?

See the SPA project template.

>Is it necessary to use CookieAuthentication and ExternalSignInCookie MWs or not?

 Yes, since your users will be entering AD credentials using the login page.

Hope I was of help.

Thanks!

**Comment by rnaab** [comment]
Thanks a lot for your help, Mohammad.

Let me to explain my idea and ask you for advise:

> 1. When using auto-login, user can't really logout unless browser process is closed to clear the credentials cache. However, you may try this approach: http://signinas.codeplex.com/

1. Idea for auto-login use case:
As you did in SPA project, user can click on Windows button (as an External login) to logon with her current AD credential, afterwards she can log out using the Log off button as well without clearing the browser's credentials cache. So why login page can't mimic auto-login by changing it as this?_If not valid token issued in the request try to login with AD user which currently logged in_ (exactly same as what takes place now by pushing the Windows button in your SPA sample). _This will be done directly on page load (= auto login)._ 

> 2. If users will be entering AD credentials in the login page, Then this is a regular cookies authentication (The only difference is that you are validating against AD rather than the DB).

2. I'm thinking about having just Bearer tokens for authentication by using just its [middle-ware](https://github.com/MohammadYounes/OWIN-MixedAuth/blob/master/src/SPA/App_Start/Startup.Auth.cs#L73) in my Web API server (not using cookies MW). So that authenticating AD users will be done by returning back a valid token to the client on successful login (for both auto or non-auto logins) and then all API calls will be handled by bearer tokens.

3. Is this a correct idea for design? Is it possible? 

Thanks
Reza

**Comment by rezanos** [comment]
Thanks a lot for your help Mohammad.

Let me to explain my ideas and ask you for advise:

> 1. When using auto-login, user can't really logout unless browser process is closed to clear the credentials cache. However, you may try this approach: http://signinas.codeplex.com/

1. Idea for auto-login use case:
As you did in SPA project, user can click on Windows button (as an External login) to logon with her current AD credential, afterwards she can log out using the Log off button as well without clearing the browser's credentials cache. So why login page can't mimic auto-login by changing it as this?: 
_If not valid token issued in the request try to login with AD user which currently logged in_ _**exactly same as what Windows button is doing now in your SPA sample** But this will be put directly on page load (= auto login)._

> 2. If users will be entering AD credentials in the login page, Then this is a regular cookies authentication (The only difference is that you are validating against AD rather than the DB).

2. I'm thinking about having **just the Bearer tokens** for authentication by using just its middle-ware in my Web API server (not cookies MW). So that authenticating AD users will be done by returning back a valid token to the client on successful login (for both auto or non-auto logins) and then all API calls will be handled by bearer tokens. Is this a correct idea for design?



Thanks
Reza.

**Comment by MohammadYounes** [comment]
> afterwards she can log out using the Log off button as well without clearing the browser's credentials cache. 

What I meant was:

Using Windows authentication, when you logout, the browser will cache the windows credentials and clicking windows login will not prompt you for username/password - even if client settings are set to "Prompt for user name and password".

> I'm thinking about having just the Bearer tokens 

I haven't tried bearer token only setup before. Try it and let us know your findings!

**Comment by Bykiev** [comment]
@aproad, hi, I need to implement the same thing, are you able to make it working? If so, can you share with sample project?
