### ISSUE TITLE
Difference Between OWIN-MixedAuth vs. MVC5-MixedAuth

### ISSUE THREAD

**Issue by Pradeep24985** [MohammadYounes/OWIN-MixedAuth#6]
HI,

I have both solution OWIN-MixedAuth as well as MVC5-MixedAuth. Both has same functionality but different implementation. Just curious, which one is better or best to use?

Thanks

**Comment by MohammadYounes** [comment]
Hi,

I recommend using [OWIN-MixedAuth], because its modular and works seamlessly with other authentication providers.

All you need is [MohammadYounes.Owin.Security.MixedAuth.dll](https://github.com/MohammadYounes/OWIN-MixedAuth/tree/master/src/MohammadYounes.Owin.Security.MixedAuth), other projects are just samples.

 [MVC5-MixedAuth] is more of a proof of concept that makes mixed authentication appear as if its an external provider.

Thanks.

[OWIN-MixedAuth]: https://github.com/MohammadYounes/OWIN-MixedAuth
[MVC5-MixedAuth]: https://github.com/MohammadYounes/MVC5-MixedAuth

**Comment by Pradeep24985** [comment]
Thanks :)
